(** A client-assigned order identifier.

    Clients choose their own order IDs before submitting, so they can refer
    to an order (e.g., to cancel it) without waiting for the exchange to
    respond with a server-side order ID. Client order IDs are scoped per
    participant — two different clients can independently choose the same ID
    without conflict.

    This is distinct from [Order_id.t], which is the exchange's internal,
    globally-unique identifier used for price-time priority and internal
    bookkeeping. *)

open! Core

type t [@@deriving sexp, bin_io, compare, equal, hash, string]

include Comparable.S with type t := t
include Hashable.S with type t := t

(** Wrap/unwrap the underlying integer. Exposed directly because the client
    chooses these IDs — they are not generated by the exchange. *)
val of_int : int -> t

val to_int : t -> int
