(** A unique identifier for an order on the exchange.

    Order IDs are assigned sequentially by the matching engine when an order
    is accepted. They are never reused within a trading session. *)

open! Core

type t [@@deriving sexp, bin_io, compare, equal, hash, string]

include Comparable.S with type t := t
include Hashable.S with type t := t

(** {2 Generation}

    Order IDs should only be generated by the matching engine. The
    [Generator] module encapsulates this to make it harder to accidentally
    create order IDs from arbitrary integers elsewhere in the code. *)

module Generator : sig
  type order_id := t
  type t [@@deriving sexp_of]

  val create : unit -> t
  val next : t -> order_id
end

(** {2 Testing}

    Integer conversion functions exposed just for testing purposes. *)

module For_testing : sig
  val to_int : t -> int
  val of_int : int -> t
end
